### ISSUE TITLE
v2.8.1 release maintenance checklist

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#1069]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions) (#1072)
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook) (#1070)
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity) (#1071)
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases) (https://github.com/rancher/rancher-docs/releases/tag/initial-snapshot-v2.8.1)
- [x] Update Algolia search index
