### ISSUE TITLE
v2.7.10 release maintenance checklist

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#1078]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions)(https://github.com/rancher/rancher-docs/pull/1100)
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook)(https://github.com/rancher/rancher-docs/pull/1101) (refer to value of `CATTLE_RANCHER_WEBHOOK_VERSION` in `package/Dockerfile` on rancher/rancher)
- [x] ~~Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity)~~
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)(https://github.com/rancher/rancher-docs/releases/tag/initial-snapshot-v2.7.10)
- [x] ~~Update Algolia search index~~
