### ISSUE TITLE
v2.8.3 Release Maintenance Checklist

### ISSUE THREAD

**Issue by sunilarjun** [rancher/rancher-docs#1169]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions) (https://github.com/rancher/rancher-docs/pull/1178)
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook) (refer to value of `CATTLE_RANCHER_WEBHOOK_VERSION` in `package/Dockerfile` on rancher/rancher (location: https://github.com/rancher/rancher/blob/v2.8.3-rc6/build.yaml) (https://github.com/rancher/rancher-docs/pull/1180)
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity) (https://github.com/rancher/rancher-docs/pull/1179)
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases) (https://github.com/rancher/rancher-docs/releases/tag/initial-snapshot-v2.8.3)
- [x] Update Algolia search index
