### ISSUE TITLE
v2.7.12 Release Maintenance Checklist

### ISSUE THREAD

**Issue by sunilarjun** [rancher/rancher-docs#1177]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions) (https://github.com/rancher/rancher-docs/pull/1200)
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook) (refer to value of `CATTLE_RANCHER_WEBHOOK_VERSION` in `package/Dockerfile` on [rancher/rancher](https://github.com/rancher/rancher/blob/v2.7.12-rc2/package/Dockerfile), currently on RC2) (https://github.com/rancher/rancher-docs/pull/1181)
- [x] ~~Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity)~~ Will be handled in [1169](https://github.com/rancher/rancher-docs/issues/1169)
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases) (https://github.com/rancher/rancher-docs/releases/tag/initial-snapshot-v2.7.12)
- [x] Update Algolia search index
