### ISSUE TITLE
v2.8-Next1 Release Maintenance Checklist

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#1233]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions) - https://github.com/rancher/rancher-docs/pull/1265
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook) - https://github.com/rancher/rancher-docs/pull/1267
  - >= 2.8.3: see `webhookVersion` in `build.yaml` on rancher/rancher
  - < 2.8.3: see `CATTLE_RANCHER_WEBHOOK_VERSION` in `package/Dockerfile` on rancher/rancher
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity) - https://github.com/rancher/rancher-docs/pull/1273
- [x] Update the [CSP adapter compatibility matrix](https://ranchermanager.docs.rancher.com/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter#rancher-vs-adapter-compatibility-matrix) - https://github.com/rancher/rancher-docs/pull/1269
  - >= 2.8.3: see `cspAdapterMinVersion` in `build.yaml` on rancher/rancher
  - < 2.8.3: see `CATTLE_CSP_ADAPTER_MIN_VERSION` in `package/Dockerfile` on rancher/rancher
- ~~[ ] Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)~~ - omitting this cycle as we're reevaluating the design and contents of the table
- [x] Update the [deprecated features table](https://ranchermanager.docs.rancher.com/faq/deprecated-features-in-v2.5) - https://github.com/rancher/rancher-docs/pull/1271
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)
- [x] Update Algolia search index
