### ISSUE TITLE
v2.8.x - Rancher Manager Release Maintenance Task Checklist 

### ISSUE THREAD

**Issue by LucasSaintarbor** [rancher/rancher-docs#1382]
## [v2.8.x - Rancher Manager Release Maintenance Task Checklist](https://confluence.suse.com/display/RD/Rancher+Manager+Release+Maintenace+Task+Checklist+Template)
- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions)
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook)
  -  >= 2.8.3: see `webhookVersion` in `build.yaml` on rancher/rancher
  - < 2.8.3: see `CATTLE_RANCHER_WEBHOOK_VERSION` in `package/Dockerfile` on rancher/rancher
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity)
- [x] Update the [CSP adapter compatibility matrix](https://ranchermanager.docs.rancher.com/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter#rancher-vs-adapter-compatibility-matrix)
  - >= 2.8.3: see `cspAdapterMinVersion` in `build.yaml` on rancher/rancher
  - < 2.8.3: see `CATTLE_CSP_ADAPTER_MIN_VERSION` in `package/Dockerfile` on rancher/rancher
- [x] Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)
- [x] Update the [deprecated features table](https://ranchermanager.docs.rancher.com/faq/deprecated-features-in-v2.5)
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)
- [x] Update Algolia search index
