### ISSUE TITLE
v2.9.1 - Rancher Manager Release Maintenance Task Checklist

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#1424]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions): https://github.com/rancher/rancher-docs/pull/1434
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook): https://github.com/rancher/rancher-docs/pull/1436
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity): https://github.com/rancher/rancher-docs/pull/1437
- [x] Update the [CSP adapter compatibility matrix](https://ranchermanager.docs.rancher.com/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter#rancher-vs-adapter-compatibility-matrix): https://github.com/rancher/rancher-docs/pull/1439
- ~Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)~
- [x] Update the [deprecated features table](https://ranchermanager.docs.rancher.com/faq/deprecated-features): https://github.com/rancher/rancher-docs/pull/1441
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)
- [ ] ~Update Algolia search index~ - will be handled as part of https://github.com/rancher/rancher-docs/issues/1428.

**Comment by martyav** [comment]
@btat I included the "Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)" item as its part of the template on Confluence, but looking back over the past few releases, we don't seem to be updating that table with each release?

**Comment by btat** [comment]
> @btat I included the "Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)" item as its part of the template on Confluence, but looking back over the past few releases, we don't seem to be updating that table with each release?
> 
> https://github.com/rancher/rancher-docs/commits/main/docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md

Per discussion, we're deferring updates to that pending an overhaul of the section.
