### ISSUE TITLE
v2.8.7 - Rancher Manager Release Maintenance Task Checklist

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#1428]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions): https://github.com/rancher/rancher-docs/pull/1433
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook): https://github.com/rancher/rancher-docs/pull/1435
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity): https://github.com/rancher/rancher-docs/pull/1437
- [x] Update the [CSP adapter compatibility matrix](https://ranchermanager.docs.rancher.com/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter#rancher-vs-adapter-compatibility-matrix): https://github.com/rancher/rancher-docs/pull/1438
- ~Update the [Feature Charts table](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher#feature-charts)~
- [x] Update the [deprecated features table](https://ranchermanager.docs.rancher.com/faq/deprecated-features): https://github.com/rancher/rancher-docs/pull/1440
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)
- [x] Update Algolia search index

**Comment by martyav** [comment]
We're omitting the feature charts item until we overhaul that table
