### ISSUE TITLE
v2.8.8 - Rancher Manager Release Maintenance Task Checklist

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#1463]
This issue is to track tasks that need to be done every release regardless of whether the release has new feature content or not.

- [x] Update the [versions table](https://ranchermanager.docs.rancher.com/versions): #1470 
- [x] Update the [Rancher:webhook version mapping table](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook):  #1471 
- [x] Update the [CNI popularity table](https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers#cni-community-popularity): #1478 
- [x] Update the [CSP adapter compatibility matrix](https://ranchermanager.docs.rancher.com/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter#rancher-vs-adapter-compatibility-matrix): #1473 
- [x] Update the [deprecated features table](https://ranchermanager.docs.rancher.com/faq/deprecated-features): #1472 
- [x] Create a new [release](https://github.com/rancher/rancher-docs/releases)
- [x] Update Algolia search index
