### ISSUE TITLE
Add a glossary of Rancher-specific terms

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#358]
**Summary:**
Rancher (and other SUSE projects/products) use some jargon that can be confusing for newbies. 

**Details:**

Kubernetes already has some overhead in the form of jargon ("charts", "pods", etc.)

Rancher and other SUSE projects and products also come with their own jargon. It can sometimes be difficult to tell if something is a general Kubernetes term or if it's specific to Rancher or RKE.

Examples: 
* Rancher using "project" for, roughly, "namespace" (I realize this is because projects predate namespaces)
* RKE 2 using "machine" for "node"

Let's compile a list of our jargon and put it in the docs as a glossary.

---

The glossary pages we added to the docset include a lot of HTML tags. This note was originally listed on the glossary page files, explaining why:

> This page uses HTML definition list tags. dl indicates the start and end of a definition list. dt indicates the defined term, and dd the definition. These will stay in place until we upgrade to Docusaurus 3 and are able to add the remark-definition-list plugin for native Markdown syntax. We are currently blocked as the plugin requires a handler that isn't currently exposed. See https://github.com/facebook/docusaurus/discussions/8743#discussioncomment-6085581 and https://github.com/facebook/docusaurus/pull/9674

More context on this from #1125:

> We (@martyav & @sunilarjun) looked into adding a plugin that would provide native Markdown syntax for definition lists. We landed on this [page ](https://docusaurus.community/knowledge/markdown/definition-lists/), which has instructions on adding remark-deflist ([repo](https://github.com/Symbitic/remark-plugins/blob/master/packages/remark-deflist/README.md)) to your Docusaurus instance, but the instructions didn't seem to work for our config. I tried remark-definition-list ([repo](https://github.com/wataru-chocola/remark-definition-list)), but that didn't work either. While looking for a solution, I ran across this https://github.com/facebook/docusaurus/discussions/8743#discussioncomment-7778521on an https://github.com/facebook/docusaurus/discussions/8743complaining that the instructions for adding Remark plugins needed improvement. It seems that the plugins need a remark-rehype handler to be configured. There was a https://github.com/facebook/docusaurus/pull/9674to add this functionality to the Docusaurus config file, but I don't think it's available yet on Docusaurus 2. We might need to upgrade to Docusaurus 3. In the meantime, the HTML tags are perfectly functional.

**Comment by martyav** [comment]
Terms to cover:

- Catalog vs apps and marketplace
- Downstream
- Rancher server

**Comment by sunilarjun** [comment]
Core concepts/terms from Fleet to be considered: https://fleet.rancher.io/concepts

**Comment by martyav** [comment]
Installing/Upgrading Rancher includes a glossary section: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade

**Comment by martyav** [comment]
### Terms - P1

- [ ] Rancher Prime
> Version: 2.7, 2.8
> Alternatives: Rancher Enterprise
- [ ] Community
- [ ] Rancher CLI
- [ ] UI
> Alternatives: Rancher UI, Rancher interface
- [ ] Rancher Kubernetes API (RK-API)
> Version: 2.8
- [ ] RKE
- [ ] RKE2
- [ ] K3s
- [ ] Rancher server
> Alternatives: local server, upstream server
- [ ] Rancher-managed cluster
> Alternatives: downstream cluster
- [ ] PSA - K8s
- [ ] (PSACT)
- [ ] PSP - K8s
- [ ] Extensions
- [ ] Catalog vs apps and marketplace
- [ ] Node template
- [ ] Project

### Terms - P2

- [ ] Fleet

**Comment by martyav** [comment]
From #1125:

> For the purposes of dividing up the word on definitions --
>
> @LucasSaintarbor, could you do Managed Clusters through Rancher Enterprise, and @sunilarjun could you take RK-API through Upstream clusters? I tried to do it evenly so that we each have 8 or 9 entries.
>
> If we add more it should be roughly,
> Me - Icons, Numbers, Symbols to L
> Lucas - M to Rancher E
> Sunil - Rancher F to Z
>
> If something is already filled out, feel free to modify and review.
