### ISSUE TITLE
Refresh info for contributors

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#795]
We have a lot of information about contributing in our internal docs. It would be helpful for both internal and external contributors if some of the information was placed in this repo, as it would be easier to find and link to.

Some areas we could address:

- [x] The README needs more details about how to navigate the repo, edit versioned docs, and move pages. If it gets too long maybe we could have abbreviated instructions on the README covering basics, and another, more detailed file describing less-common tasks.
- [x] We currently have a page on Contributing here -- https://ranchermanager.docs.rancher.com/contribute-to-rancher. The information about docs is low on the page and points to the older 2.x repo. -- Addressed in #805 
- [x] We should have another look at our issue templates and update them as needed.
